services:
  - type: web
    name: tasktrack-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
